spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/quotes-collection
    username: nadezhda
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    show-sql: true
server:
  port: 8080
